USE [VAIVOA]
GO

/****** Object:  Table [dbo].[TB_PESSOA_CARTAO]    Script Date: 28/05/2021 15:59:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_PESSOA_CARTAO](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[email] [varchar](50) NULL,
	[dataCriacao] [datetime] NULL,
	[numeroCartaoVirtual] [varchar](20) NULL,
 CONSTRAINT [PK_TB_PESSOA_CARTAO] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


